name: build <fcs-core-2> adocs

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'fcs-core-2/**'
      - '.github/workflows/build-fcs-core-2-adoc.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor

    steps:
      - uses: actions/checkout@v4

      - name: Build HTML
        run: asciidoctor -v -D docs -a data-uri --backend=html5 -o fcs-core-2.html fcs-core-2/index.adoc

      - name: Build PDF
        run: asciidoctor-pdf -v -D docs -o fcs-core-2.pdf fcs-core-2/index.adoc

      - name: Copy attachments
        run: cp -R fcs-core-2/attachments docs/

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: fcs-core-2-specs
          path: docs/*
